const {contextBridge,ipcRenderer}=require('electron');

/* KM_PRELOAD_HARDEN_V1 */
function kmSafeExternalUrl(url){
  try{
    const u=String(url||'').trim();
    if(!u) return '';
    const low=u.toLowerCase();
    if(low.startsWith('https://')||low.startsWith('http://')||low.startsWith('mailto:')) return u;
    return '';
  }catch(e){ return ''; }
}
function kmSafeFsPath(p){
  try{
    const s=String(p||'');
    if(!s) return '';
    if(/[\0]/.test(s)) return '';
    return s;
  }catch(e){ return ''; }
}
contextBridge.exposeInMainWorld('kmNative',{
  original:{
    selectFolder:()=>ipcRenderer.invoke('km:original:selectFolder'),
    analyze:(root)=>ipcRenderer.invoke('km:original:analyze',root),
    clean:(root)=>ipcRenderer.invoke('km:original:clean',root),
    repair:(root)=>ipcRenderer.invoke('km:original:repair',root)
  },
  persistence:{
    writeSnapshot:(key,json)=>ipcRenderer.invoke('km:persist:writeSnapshot',{key,json}),
    readSnapshot:()=>ipcRenderer.invoke('km:persist:readSnapshot')
  },
  file:{
    saveDesktop:(request)=>ipcRenderer.invoke('km:file:saveDesktop',request),
    writeDesktop:(request)=>ipcRenderer.invoke('km:file:writeDesktop',request),
    readBytes:(filePath)=>ipcRenderer.invoke('km:file:readBytes',filePath),
    pickOpen:(request)=>ipcRenderer.invoke('km:file:pickOpen',request||{}),
    pickOpenPath:(request)=>ipcRenderer.invoke('km:file:pickOpenPath',request||{}),
    readBundled:(rel)=>ipcRenderer.invoke('km:file:readBundled',rel||''),
    openBundled:(rel)=>ipcRenderer.invoke('km:file:openBundled',rel||'')
  },
  discipline:{
    savePdf:(req)=>ipcRenderer.invoke('km:discipline:savePdf',req||{}),
    readPdf:(req)=>ipcRenderer.invoke('km:discipline:readPdf',req||{}),
    removePdf:(req)=>ipcRenderer.invoke('km:discipline:removePdf',req||{})
  },
  personDoc:{
    savePdf:(req)=>ipcRenderer.invoke('km:persondoc:savePdf',req||{}),
    readPdf:(req)=>ipcRenderer.invoke('km:persondoc:readPdf',req||{}),
    removePdf:(req)=>ipcRenderer.invoke('km:persondoc:removePdf',req||{})
  },
  /* KM_SOLDIER_CARD_ARCHIVE_V1 — Անձի քարտ PDF արխիվ (զինծառայողների քարտեր) */
  soldierCardArchive:{
    list:(req)=>ipcRenderer.invoke('km:soldiercard:list',req||{}),
    listAll:()=>ipcRenderer.invoke('km:soldiercard:listAll'),
    save:(req)=>ipcRenderer.invoke('km:soldiercard:save',req||{}),
    scanAndSave:(req)=>ipcRenderer.invoke('km:soldiercard:scanAndSave',req||{}),
    read:(req)=>ipcRenderer.invoke('km:soldiercard:read',req||{}),
    remove:(req)=>ipcRenderer.invoke('km:soldiercard:remove',req||{})
  },
  bns:{ invoke:(args)=>ipcRenderer.invoke('bns-client-invocation',args==null?null:args) },
  bro:{ invoke:(args)=>ipcRenderer.invoke('bro-client-invocation',args==null?null:args) },
  convert:{
    run:(request)=>ipcRenderer.invoke('km:convert:run',request),
    folder:(request)=>ipcRenderer.invoke('km:convert:folder',request||{}),
    mergePdf:(request)=>ipcRenderer.invoke('km:convert:mergePdf',request||{}),
    splitPdf:(request)=>ipcRenderer.invoke('km:convert:splitPdf',request||{}),
    imagesPdf:(request)=>ipcRenderer.invoke('km:convert:imagesPdf',request||{}),
    onProgress:(cb)=>{
      const fn=(_,ev)=>cb(ev);
      ipcRenderer.on('km:convert:progress',fn);
      return ()=>ipcRenderer.removeListener('km:convert:progress',fn);
    }
  },
  shell:{
    showItemInFolder:(filePath)=>{ const p=kmSafeFsPath(filePath); if(!p) return Promise.reject(new Error('Blocked path')); return ipcRenderer.invoke('km:shell:showItemInFolder',p); },
    openPath:(targetPath)=>{ const p=kmSafeFsPath(targetPath); if(!p) return Promise.reject(new Error('Blocked path')); return ipcRenderer.invoke('km:shell:openPath',p); },
    openExternal:(url)=>{ const u=kmSafeExternalUrl(url); if(!u) return Promise.reject(new Error('Blocked external URL')); return ipcRenderer.invoke('km:shell:openExternal',u); }
  },
  macro:{
    run:(request)=>ipcRenderer.invoke('km:macro:run',request)
  },
  print:{
    pdf:(request)=>ipcRenderer.invoke('km:print:pdf',request),
    printers:()=>ipcRenderer.invoke('km:print:printers'),
    native:(request)=>ipcRenderer.invoke('km:print:native',request)
  },
  backup:{
    run:(label)=>ipcRenderer.invoke('km:backup:run',label),
    list:()=>ipcRenderer.invoke('km:backup:list'),
    restore:(nameOrReq)=>{
      const req=nameOrReq&&typeof nameOrReq==='object'?nameOrReq:{name:nameOrReq};
      return ipcRenderer.invoke('km:backup:restore',req);
    },
    exportEncrypted:(password)=>ipcRenderer.invoke('km:backup:exportEncrypted',password),
    importEncrypted:(req)=>ipcRenderer.invoke('km:backup:importEncrypted',req)
  },
  usb:{
    export:(password,opts)=>ipcRenderer.invoke('km:usb:export',password,opts||{}),
    import:(req)=>ipcRenderer.invoke('km:usb:import',req||{}),
    importLibrary:(folder)=>ipcRenderer.invoke('km:usb:importLibrary',folder||''),
    importPhotos:(folder)=>ipcRenderer.invoke('km:usb:importPhotos',folder||'')
  },
  audit:{
    append:(entry)=>ipcRenderer.invoke('km:audit:append',entry),
    list:(limit,query)=>ipcRenderer.invoke('km:audit:list',limit,query||'')
  },
  hishoxutyun:{
    append:(entry)=>ipcRenderer.invoke('km:hishoxutyun:append',entry||{}),
    list:(req)=>ipcRenderer.invoke('km:hishoxutyun:list',req||{}),
    sections:()=>ipcRenderer.invoke('km:hishoxutyun:sections')
  },
  photo:{
    save:(req)=>ipcRenderer.invoke('km:photo:save',req||{})
  },
  errorLog:{
    append:(entry)=>ipcRenderer.invoke('km:error:log',entry||{}),
    path:()=>ipcRenderer.invoke('km:error:logPath')
  },
  security:{
    get:()=>ipcRenderer.invoke('km:security:get'),
    set:(cfg)=>ipcRenderer.invoke('km:security:set',cfg),
    verify:(req)=>ipcRenderer.invoke('km:security:verify',req),
    loginAdmin:(req)=>ipcRenderer.invoke('km:security:loginAdmin',req||{}),
    verifySession:(token)=>ipcRenderer.invoke('km:security:verifySession',token||''),
    clearSession:()=>ipcRenderer.invoke('km:security:clearSession'),
    loginHint:()=>ipcRenderer.invoke('km:security:loginHint')
  },
  users:{
    list:(req)=>ipcRenderer.invoke('km:users:list',req||{}),
    saveAdmin:(req)=>ipcRenderer.invoke('km:users:saveAdmin',req||{}),
    deleteAdmin:(req)=>ipcRenderer.invoke('km:users:deleteAdmin',req||{}),
    saveUser:(req)=>ipcRenderer.invoke('km:users:saveUser',req||{}),
    ensure:(req)=>ipcRenderer.invoke('km:users:ensure',req||{}),
    register:(req)=>ipcRenderer.invoke('km:users:register',req||{}),
    issueCode:(req)=>ipcRenderer.invoke('km:users:issueCode',req||{}),
    deleteUser:(req)=>ipcRenderer.invoke('km:users:deleteUser',req||{}),
    restoreUser:(req)=>ipcRenderer.invoke('km:users:restoreUser',req||{}),
    purgeDeleted:(req)=>ipcRenderer.invoke('km:users:purgeDeleted',req||{}),
    loginUser:(req)=>ipcRenderer.invoke('km:users:loginUser',req||{}),
    deviceBound:()=>ipcRenderer.invoke('km:users:deviceBound'),
    clearDeviceBound:()=>ipcRenderer.invoke('km:users:clearDeviceBound'),
    logActivity:(req)=>ipcRenderer.invoke('km:users:logActivity',req||{}),
    listActivity:(req)=>ipcRenderer.invoke('km:users:listActivity',req||{})
  },
  orgEntry:{
    isUnlocked:(req)=>ipcRenderer.invoke('km:org:isUnitUnlocked',req||{}),
    verify:(req)=>ipcRenderer.invoke('km:org:verifyUnitEntry',req||{}),
    kodList:(req)=>ipcRenderer.invoke('km:org:unitKodList',req||{}),
    kodStatus:(req)=>ipcRenderer.invoke('km:org:unitKodStatus',req||{}),
    kodSet:(req)=>ipcRenderer.invoke('km:org:unitKodSet',req||{}),
    kodClear:(req)=>ipcRenderer.invoke('km:org:unitKodClear',req||{}),
    seedGet:()=>ipcRenderer.invoke('km:org:seedGet'),
    seedWrite:(org)=>ipcRenderer.invoke('km:org:seedWrite',org||{}),
    archivesGet:(opts)=>ipcRenderer.invoke('km:org:archivesGet',opts||{}),
    archivesWrite:(list)=>ipcRenderer.invoke('km:org:archivesWrite',list||[])
  },
  license:{
    status:()=>ipcRenderer.invoke('km:license:status'),
    activate:(code)=>ipcRenderer.invoke('km:license:activate',code),
    resetOnLogout:()=>ipcRenderer.invoke('km:license:resetOnLogout'),
    getPendingCode:()=>ipcRenderer.invoke('km:license:getPendingCode'),
    clearPendingCode:()=>ipcRenderer.invoke('km:license:clearPendingCode'),
    stageNext:()=>ipcRenderer.invoke('km:license:stageNext'),
    adminOverview:(req)=>ipcRenderer.invoke('km:license:adminOverview',req||{}),
    clearUsedReceipts:(req)=>ipcRenderer.invoke('km:license:clearUsedReceipts',req||{})
  },
  vault:{
    status:()=>ipcRenderer.invoke('km:vault:status'),
    setup:(keys)=>ipcRenderer.invoke('km:vault:setup',keys||{}),
    unlock:(req)=>ipcRenderer.invoke('km:vault:unlock',req||{}),
    rebind:(keys)=>ipcRenderer.invoke('km:vault:rebind',keys||{}),
    rotate:(req)=>ipcRenderer.invoke('km:vault:rotate',req||{}),
    gate:()=>ipcRenderer.invoke('km:vault:gate'),
    verifySeal:(seal)=>ipcRenderer.invoke('km:vault:verifySeal',seal||null)
  },
  kod:{
    activate:()=>ipcRenderer.invoke('km:kod:activate'),
    consumeAutoLogin:()=>ipcRenderer.invoke('km:kod:consumeAutoLogin')
  },
  login:{
    consumeUiWipe:()=>ipcRenderer.invoke('km:login:consumeUiWipe')
  },
  install:{
    get:()=>ipcRenderer.invoke('km:install:get')
  },
  onLicenseChanged:(cb)=>ipcRenderer.on('km:license:changed',()=>cb()),
  export:{
    scheduleExcel:(payload)=>ipcRenderer.invoke('km:export:scheduleExcel',payload),
    batchPrintPdf:(payload)=>ipcRenderer.invoke('km:export:batchPrintPdf',payload),
    dutyOrderWord:(payload)=>ipcRenderer.invoke('km:export:dutyOrderWord',payload),
    orderDraftWord:(payload)=>ipcRenderer.invoke('km:export:orderDraftWord',payload),
    troopStructureExcel:(payload)=>ipcRenderer.invoke('km:export:troopStructureExcel',payload)
  },
  troop:{
    importXlsx:(req)=>ipcRenderer.invoke('km:troop:importXlsx',req||{})
  },
  templates:{
    get:()=>ipcRenderer.invoke('km:templates:get'),
    save:(list)=>ipcRenderer.invoke('km:templates:save',list)
  },
  settings:{
    get:()=>ipcRenderer.invoke('km:settings:get'),
    set:(patch)=>ipcRenderer.invoke('km:settings:set',patch)
  },
  helpBot:{
    llmRequest:(req)=>ipcRenderer.invoke('km:helpBot:llmRequest',req||{}),
    ttsFetch:(req)=>ipcRenderer.invoke('km:helpBot:ttsFetch',req||{}),
    translate:(req)=>ipcRenderer.invoke('km:helpBot:translate',req||{}),
    clearHistory:(req)=>ipcRenderer.invoke('km:bot:clearHistory',req||{}),
    ask:(query)=>ipcRenderer.invoke('km:helpBot:ask', String(query || ''))
  },
  renderPolicy:{
    setForceSoftwareRender:(on)=>ipcRenderer.invoke('km:render:setForceSoftware',!!on)
  },

  botRag:{
    status:()=>ipcRenderer.invoke('km:botRag:status'),
    sync:(req)=>ipcRenderer.invoke('km:botRag:sync',req||{}),
    search:(req)=>ipcRenderer.invoke('km:botRag:search',req||{}),
    multiStep:(req)=>ipcRenderer.invoke('km:botRag:multiStep',req||{}),
    webSearch:(req)=>ipcRenderer.invoke('km:botRag:webSearch',req||{}),
    settings:(patch)=>ipcRenderer.invoke('km:botRag:settings',patch||null)
  },
  botKnowledge:{
    status:()=>ipcRenderer.invoke('km:botKnowledge:status'),
    search:(req)=>ipcRenderer.invoke('km:botKnowledge:search',req||{}),
    searchSimple:(req)=>ipcRenderer.invoke('km:botKnowledge:searchSimple',req||{}),
    add:(req)=>ipcRenderer.invoke('km:botKnowledge:add',req||{}),
    flush:(req)=>ipcRenderer.invoke('km:botKnowledge:flush',req||{}),
    reindex:(req)=>ipcRenderer.invoke('km:botKnowledge:reindex',req||{}),
    refreshFts:(req)=>ipcRenderer.invoke('km:botKnowledge:refreshFts',req||{})
  },
  library:{
    stats:(opts)=>ipcRenderer.invoke('km:library:stats',opts||{}),
    list:(type,opts)=>ipcRenderer.invoke('km:library:list',type,opts||{}),
    add:(req)=>ipcRenderer.invoke('km:library:add',req||{}),
    importFolder:(req)=>ipcRenderer.invoke('km:library:importFolder',req||{}),
    remove:(req)=>ipcRenderer.invoke('km:library:remove',req||{}),
    removeAll:(req)=>ipcRenderer.invoke('km:library:removeAll',req||{}),
    knowledgeEpoch:()=>ipcRenderer.invoke('km:library:knowledgeEpoch'),
    bumpKnowledge:(reason)=>ipcRenderer.invoke('km:library:bumpKnowledge',reason||'manual'),
    open:(req)=>ipcRenderer.invoke('km:library:open',req||{}),
    lawsStats:()=>ipcRenderer.invoke('km:library:lawsStats'),
    lawsList:(section,opts)=>ipcRenderer.invoke('km:library:lawsList',section,opts||{}),
    lawsAdd:(req)=>ipcRenderer.invoke('km:library:lawsAdd',req||{}),
    lawsImportFolder:(section)=>ipcRenderer.invoke('km:library:lawsImportFolder',section||'laws'),
    lawsRemove:(req)=>ipcRenderer.invoke('km:library:lawsRemove',req||{}),
    lawsFindByNumber:(req)=>ipcRenderer.invoke('km:library:lawsFindByNumber',req||{}),
    lawsEnsureArlis:(req)=>ipcRenderer.invoke('km:library:lawsEnsureArlis',req||{}),
    lawsEnsureDrill:()=>ipcRenderer.invoke('km:library:lawsEnsureDrill'),
    lawsEnsureStatutes:(req)=>ipcRenderer.invoke('km:library:lawsEnsureStatutes',req||{}),
    lawsEnsureSoldierRights:()=>ipcRenderer.invoke('km:library:lawsEnsureSoldierRights'),
    lawsEnsureArlisMilitary:(req)=>ipcRenderer.invoke('km:library:lawsEnsureArlisMilitary',req||{}),
    lawsRepair:(req)=>ipcRenderer.invoke('km:library:lawsRepair',req||{}),
    lawsArlisMilitaryProgress:(req)=>ipcRenderer.invoke('km:library:lawsArlisMilitaryProgress',req||{}),
    onArlisMilitaryProgress:(fn)=>{
      const h=(_,p)=>{try{fn&&fn(p);}catch(e){}};
      ipcRenderer.on('km:library:arlisMilitaryProgress',h);
      return()=>ipcRenderer.removeListener('km:library:arlisMilitaryProgress',h);
    },
    lawsRead:(req)=>ipcRenderer.invoke('km:library:lawsRead',req||{}),
    searchContent:(req)=>ipcRenderer.invoke('km:library:searchContent',req||{}),
    printPdf:(req)=>ipcRenderer.invoke('km:library:printPdf',req||{}),
    editPdf:(req)=>ipcRenderer.invoke('km:library:editPdf',req||{}),
    saveHtml:(req)=>ipcRenderer.invoke('km:library:saveHtml',req||{}),
    savePdfFromWord:(req)=>ipcRenderer.invoke('km:library:savePdfFromWord',req||{}),
    extractPdfText:(req)=>ipcRenderer.invoke('km:library:extractPdfText',req||{}),
    savePdfFromHtml:(req)=>ipcRenderer.invoke('km:library:savePdfFromHtml',req||{}),
    convertLawsHtmlToPdf:(req)=>ipcRenderer.invoke('km:library:convertLawsHtmlToPdf',req||{}),
    onHtmlToPdfProgress:(fn)=>{
      const h=(_,p)=>{try{fn&&fn(p);}catch(e){}};
      ipcRenderer.on('km:library:htmlToPdfProgress',h);
      return()=>ipcRenderer.removeListener('km:library:htmlToPdfProgress',h);
    }
  },
  pdfTranslate:{
    probe:()=>ipcRenderer.invoke('km:pdfTranslate:probe'),
    run:(req)=>ipcRenderer.invoke('km:pdfTranslate:run',req||{})
  },
  fonts:{
    list:()=>ipcRenderer.invoke('km:fonts:list'),
    add:(req)=>ipcRenderer.invoke('km:fonts:add',req||{}),
    remove:(req)=>ipcRenderer.invoke('km:fonts:remove',req||{}),
    ensureRegistered:()=>ipcRenderer.invoke('km:fonts:ensureRegistered')
  },
  app:{
    quit:()=>ipcRenderer.invoke('km:app:quit'),
    minimize:()=>ipcRenderer.invoke('km:app:minimize'),
    info:()=>ipcRenderer.invoke('km:app:info'),
    relaunch:()=>ipcRenderer.invoke('km:app:relaunch'),
    factoryReset:(req)=>ipcRenderer.invoke('km:app:factoryReset',req||{})
  },
  sync:{
    export:(json)=>ipcRenderer.invoke('km:sync:export',json),
    import:()=>ipcRenderer.invoke('km:sync:import')
  },
  net:{
    status:()=>ipcRenderer.invoke('km:net:status'),
    start:()=>ipcRenderer.invoke('km:net:start'),
    stop:()=>ipcRenderer.invoke('km:net:stop'),
    setConfig:(patch)=>ipcRenderer.invoke('km:net:setConfig',patch||{}),
    peers:()=>ipcRenderer.invoke('km:net:peers'),
    scan:()=>ipcRenderer.invoke('km:net:scan'),
    addPeer:(host)=>ipcRenderer.invoke('km:net:addPeer',host||''),
    send:(req)=>ipcRenderer.invoke('km:net:send',req||{}),
    sendAll:(req)=>ipcRenderer.invoke('km:net:sendAll',req||{}),
    pickFile:()=>ipcRenderer.invoke('km:net:pickFile'),
    autoStart:()=>ipcRenderer.invoke('km:net:autoStart'),
    autoStop:()=>ipcRenderer.invoke('km:net:autoStop'),
    inbox:()=>ipcRenderer.invoke('km:net:inbox'),
    outbox:()=>ipcRenderer.invoke('km:net:outbox'),
    history:()=>ipcRenderer.invoke('km:net:history'),
    openInbox:()=>ipcRenderer.invoke('km:net:openInbox'),
    openOutbox:()=>ipcRenderer.invoke('km:net:openOutbox'),
    openArchive:()=>ipcRenderer.invoke('km:net:openArchive'),
    reportNow:()=>ipcRenderer.invoke('km:net:reportNow'),
    putOutbox:(req)=>ipcRenderer.invoke('km:net:putOutbox',req||{}),
    redistribute:(req)=>ipcRenderer.invoke('km:net:redistribute',req||{}),
    openFile:(req)=>ipcRenderer.invoke('km:net:openFile',req||{}),
    openUpdateStaging:()=>ipcRenderer.invoke('km:net:openUpdateStaging'),
    clearUpdateStaging:()=>ipcRenderer.invoke('km:net:clearUpdateStaging'),
    readText:(req)=>ipcRenderer.invoke('km:net:readText',req||{}),
    ping:(req)=>ipcRenderer.invoke('km:net:ping',req||{}),
    checkUpdate:(req)=>ipcRenderer.invoke('km:net:checkUpdate',req||{}),
    pullUpdate:(req)=>ipcRenderer.invoke('km:net:pullUpdate',req||{})
  },
  conversations:{
    append:(req)=>ipcRenderer.invoke('km:conversations:append',req||{}),
    list:(req)=>ipcRenderer.invoke('km:conversations:list',req||{}),
    prune:(req)=>ipcRenderer.invoke('km:conversations:prune',req||{}),
    exportKnowledge:(req)=>ipcRenderer.invoke('km:conversations:exportKnowledge',req||{}),
    ingestKnowledge:(req)=>ipcRenderer.invoke('km:conversations:ingestKnowledge',req||{}),
    flushHub:()=>ipcRenderer.invoke('km:conversations:flushHub')
  },
  retention:{
    list:(req)=>ipcRenderer.invoke('km:retention:list',req||{}),
    restore:(req)=>ipcRenderer.invoke('km:retention:restore',req||{}),
    prune:(req)=>ipcRenderer.invoke('km:retention:prune',req||{})
  },
  lanSync:{
    status:()=>ipcRenderer.invoke('km:lanSync:status'),
    setConfig:(patch)=>ipcRenderer.invoke('km:lanSync:setConfig',patch||{}),
    start:()=>ipcRenderer.invoke('km:lanSync:start'),
    stop:()=>ipcRenderer.invoke('km:lanSync:stop'),
    connect:()=>ipcRenderer.invoke('km:lanSync:connect'),
    manifest:()=>ipcRenderer.invoke('km:lanSync:manifest'),
    refreshBotKnowledge:()=>ipcRenderer.invoke('km:lanSync:refreshBotKnowledge'),
    adoptHub:(opts)=>ipcRenderer.invoke('km:lanSync:adoptHub',opts||{}),
    ensureHub:(opts)=>ipcRenderer.invoke('km:lanSync:ensureHub',opts||{}),
    pullPrefix:(prefix,opts)=>ipcRenderer.invoke('km:lanSync:pullPrefix',prefix,opts||{})
  },
  onNetEvent:(cb)=>{
    const fn=(_,ev)=>{ try{ cb(ev); }catch(e){} };
    ipcRenderer.on('km:net:event',fn);
    return ()=>ipcRenderer.removeListener('km:net:event',fn);
  },
  offNetEvent:()=>ipcRenderer.removeAllListeners('km:net:event'),
  onLanSyncEvent:(cb)=>ipcRenderer.on('km:lanSync:event',(_,ev)=>cb(ev)),
  offLanSyncEvent:()=>ipcRenderer.removeAllListeners('km:lanSync:event'),
  onBotHistoryCleared:(cb)=>ipcRenderer.on('km:bot:historyCleared',(_,ev)=>cb(ev)),
  onDisplayChanged:(cb)=>ipcRenderer.on('km:display:changed',()=>cb()),
  onHotkey:(cb)=>{
    const fn=(_,name)=>{ try{ cb(name); }catch(e){} };
    ipcRenderer.on('km:hotkey',fn);
    return ()=>ipcRenderer.removeListener('km:hotkey',fn);
  },
  sysinfo:{
    usbHistory:()=>ipcRenderer.invoke('km:sysinfo:usbHistory'),
    wifiHistory:()=>ipcRenderer.invoke('km:sysinfo:wifiHistory'),
    internetHistory:()=>ipcRenderer.invoke('km:sysinfo:internetHistory'),
    bluetoothHistory:()=>ipcRenderer.invoke('km:sysinfo:bluetoothHistory'),
    computerQuick:()=>ipcRenderer.invoke('km:sysinfo:computerQuick'),
    computerInfo:()=>ipcRenderer.invoke('km:sysinfo:computerInfo'),
    clearUsb:()=>ipcRenderer.invoke('km:sysinfo:clearUsb'),
    clearWifi:()=>ipcRenderer.invoke('km:sysinfo:clearWifi'),
    clearInternet:()=>ipcRenderer.invoke('km:sysinfo:clearInternet'),
    clearBluetooth:()=>ipcRenderer.invoke('km:sysinfo:clearBluetooth'),
    clearAll:()=>ipcRenderer.invoke('km:sysinfo:clearAll'),
    exportPdf:(req)=>ipcRenderer.invoke('km:sysinfo:exportPdf',req||{}),
    notesGet:()=>ipcRenderer.invoke('km:sysinfo:notesGet'),
    notesSet:(req)=>ipcRenderer.invoke('km:sysinfo:notesSet',req||{}),
    snapshotSave:(req)=>ipcRenderer.invoke('km:sysinfo:snapshotSave',req||{}),
    snapshotList:()=>ipcRenderer.invoke('km:sysinfo:snapshotList'),
    snapshotGet:(id)=>ipcRenderer.invoke('km:sysinfo:snapshotGet',id||'')
  }
});
